# Generated by Django 5.1.6 on 2025-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='atributo1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='atributo2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='atributo3',
            field=models.IntegerField(null=True),
        ),
    ]
