# Generated by Django 5.1.6 on 2025-05-21 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodologia', '0001_initial'),
        ('samples', '0002_sample_atributo1_sample_atributo2_sample_atributo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='metodologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='metodologia.metodologia'),
        ),
    ]
