# Generated by Django 5.1.6 on 2025-05-29 03:02

import samples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_remove_sample_atributo1_remove_sample_atributo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='anexo1',
            field=models.FileField(blank=True, null=True, upload_to=samples.models.sample_upload_path),
        ),
        migrations.AlterField(
            model_name='sample',
            name='anexo2',
            field=models.FileField(blank=True, null=True, upload_to=samples.models.sample_upload_path),
        ),
    ]
