# Generated by Django 5.1.6 on 2025-05-28 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelas', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('porcentagem', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('metodologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_samples', to='metodologia.metodologia')),
            ],
        ),
    ]
