# Generated by Django 5.1.6 on 2025-05-28 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discsamples', '0001_initial'),
        ('metodologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discosample',
            name='metodologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disc_samples', to='metodologia.metodologia'),
        ),
    ]
