# Generated by Django 5.1.6 on 2025-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discsamples', '0002_alter_discosample_metodologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='discosample',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
